# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RatFinder_ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


pod 'Firebase/Core'
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database'

  # Pods for RatFinder_ios

  target 'RatFinder_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RatFinder_iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
